---
# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Blog
site_url: https://blog.iamadam.dev

extra:
  social:
    - icon: fontawesome/brands/spotify
      link: https://open.spotify.com/user/astracener
      name: Spotify

theme:
  name: material
  features:
    - header.autohide
    # - navigation.footer
  palette:
    # Palette toggle for automatic mode
    - media: (prefers-color-scheme)
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default

      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    code: Roboto Mono
    text: Roboto

plugins:
  - social:
      enabled: true
      cards: true
  - blog:
      # draft: !ENV [DRAFT, false]
      draft_if_future_date: true
      # authors_profiles: !ENV [AUTHORS_PROFILE, false]
      post_readtime: true
      blog_toc: true
      post_date_format: long
      post_excerpt: required
      archive: false
      pagination: true
  - search:
      lang: en
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
  - tags
  # - git-revision-date-localized:
  #     enable_creation_date: true
  #     enabled: !ENV
  #       - CI
  #       - false
  #     type: date
  #     fallback_to_build_date: true
  # - table-reader
