---
# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Blog
site_url: https://blog.iamadam.dev

remote_branch: gh-pages
remote_name: origin
repo_name: GitHub
repo_url: https://github.com/NeckBeardPrince/blog

extra:
  social:
    - icon: fontawesome/brands/spotify
      link: https://open.spotify.com/user/astracener
      name: Spotify

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - content.footnote.tooltips
    - header.autohide
    - navigation.expand
    # - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    # - navigation.instant.preview
    - navigation.path
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    # Palette toggle for automatic mode
    - media: (prefers-color-scheme)
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default

      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  # font:
  #   code: Roboto Mono
  #   text: Roboto

plugins:
  - tags
  - social:
      enabled: true
      cards: true
  - blog:
      draft: !ENV
        - DRAFT
        - false
      draft_if_future_date: true
      post_readtime: true
      blog_toc: true
      post_date_format: long
      post_excerpt: required
      archive: false
      pagination: true
  - search:
      lang: en
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
# Allow security.txt
exclude_docs: |-
  !.well-known
